blood_request/urls.py
from django.urls import path, include

from blood_request.views import BloodRequestView, BloodRequestListView

app_name = 'blood_request'

urlpatterns = [
    path("add_request/", BloodRequestView.as_view(), name="add_request"),
    path("list_request/", BloodRequestListView.as_view(), name="list_request")
]

bloodbank/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bloodbank import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("donor/", include('donor.urls')),
    path("blood_request/", include('blood_request.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

donor/urls.py
from django.urls import path, include

from donor.views import IndexView, DonorCreateView

app_name = 'donor'

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("add_donor/", DonorCreateView.as_view(), name="add_donor"),

]

blood_request/models.py
from django.db import models

from donor.models import BloodGroupUser


# Create your models here.
class RequestBlood(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    state = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=300, blank=True)
    address = models.CharField(max_length=500, blank=True)
    blood_group = models.ForeignKey(BloodGroupUser, on_delete=models.CASCADE)
    date = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

donor/models.py
from django.contrib.auth.models import User
from django.db import models


class BloodGroupUser(models.Model):
    name = models.CharField(max_length=5)

    def __str__(self):
        return self.name


# Create your models here.
class BloodDonor(models.Model):
    donor = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    date_of_birth = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    address = models.TextField(max_length=500, default="")
    blood_group = models.ForeignKey(BloodGroupUser, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10)
    image = models.ImageField(upload_to="")
    ready_to_donate = models.BooleanField(default=True)

    def __str__(self):
        return str(self.blood_group)

blood_request/forms.py
from django import forms
from .models import RequestBlood


class BloodRequestForm(forms.ModelForm):
    """forms for the blood request."""

    class Meta:
        model = RequestBlood
        fields = '__all__'

donor/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import BloodDonor

User = get_user_model()


class BloodDonorForm(forms.ModelForm):
    """forms for the blood donor."""
    image = forms.ImageField(required=False)

    class Meta:
        model = BloodDonor
        fields = '__all__'


class UserForm(forms.ModelForm):
    """forms for the user."""
    date_joined = forms.CharField(required=False)

    class Meta:
        model = User
        fields = '__all__'

blood_request/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from blood_request.forms import BloodRequestForm
from blood_request.models import RequestBlood


# Create your views here.
class BloodRequestView(CreateView):
    """Create view for the blood request."""
    model = RequestBlood
    form_class = BloodRequestForm
    template_name = 'request_blood.html'

    def get_context_data(self, **kwargs):
        data = super(BloodRequestView, self).get_context_data()
        if self.request.POST:
            data['form'] = self.form_class(self.request.POST)
        else:
            data['form'] = self.form_class()
        return data

    def form_valid(self, form):
        """
        This method will be used for validating forms.
        """
        context = self.get_context_data()
        form = context['form']
        # resource data validation as form at time of creating user object
        form.save()
        return redirect('donor:index')


class BloodRequestListView(ListView):
    """blood request listing."""
    template_name = 'see_all_request.html'
    model = RequestBlood
    queryset = RequestBlood.objects.all()
    context_object_name = 'requests'

donor/views.py
from django.db.models.aggregates import Count
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic.list import ListView

from donor.forms import BloodDonorForm, UserForm
from donor.models import BloodGroupUser, BloodDonor


# Create your views here.
class IndexView(ListView):
    """dashboard for the donor and requester both."""
    template_name = 'index.html'
    model = BloodGroupUser
    queryset = BloodGroupUser.objects.all()
    context_object_name = 'all_group'

    def get_queryset(self):
        return BloodGroupUser.objects.annotate(total=Count('blooddonor'))


class DonorCreateView(CreateView):
    """"donor create."""
    template_name = 'become_donor.html'
    model = BloodDonor
    form_class = BloodDonorForm

    def post(self, request, *args, **kwargs):
        user_form = UserForm(self.request.POST)
        form = BloodDonorForm(self.request.POST)
        if user_form.is_valid() and form.is_valid():
            instance_user = user_form.save()
            instance_user.save()
            user_instance = instance_user
            star_form = form.save()
            star_form.donor = user_instance
            star_form.save()
        return redirect(reverse('donor:index'))

blood_request/templates/partials/add_request_partials.html
{% load static %}
{% load widget_tweaks %}
<div class="form-group col-md-6">
    <label for="{{ field.id_for_label }}"><i style="font-weight: bold;">{{ field.label }}: {% if field.field.required %}<strong class="text-danger">*</strong>{% endif %}</i></label>
    {% render_field field class="form-control" %}
    <div class="text-danger error_class">
        {% for error in field.errors %}
          <small>* {{error}}</small><br>
        {% endfor %}
    </div>
</div>

blood_request/templates/request_blood.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body %}
<div class="container">
    <h3><i style="font-weight: bold;">Request For Blood</i></h3>
    <form method="POST" action="{% url 'blood_request:add_request' %}" novalidate>
        {% csrf_token %}
        <div class="row mt-1">
            {% include "partials/add_request_partials.html" with field=form.name %}
            {% include "partials/add_request_partials.html" with field=form.email %}
        </div>

        <div class="row mt-1">
            {% include "partials/add_request_partials.html" with field=form.phone %}
            {% include "partials/add_request_partials.html" with field=form.state %}
        </div>

        <div class="row mt-1">
            <div class="form-group col-md-12">
                {% include "partials/add_request_partials.html" with field=form.address %}
            </div>
        </div>

        <div class="row mt-1">
        <div class="form-group col-md-6">
            {% include "partials/add_request_partials.html" with field=form.blood_group %}
        </div>
        <div class="form-group col-md-6">
            {% include "partials/add_request_partials.html" with field=form.date %}
        </div>
        </div>
        <div class="row mt-1">
            {% include "partials/add_request_partials.html" with field=form.city %}
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

blood_request/templates/see_all_request.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
{% if requests %}
<h3 class="text-center">All Blood Requests</h3>
<br>
<table class="table table-sm table-bordered">
  <tr class="table-danger">
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Blood Group</th>
    <th>Donation Date</th>
    <th>State | City</th>
  </tr>
  {% for i in requests %}
    <tr>
      <td>{{i.name}}</td>
      <td>{{i.phone}}</td>
      <td>{{i.email}}</td>
      <td>{{i.blood_group}}</td>
      <td>{{i.date}}</td>
      <td>{{i.state}} | {{i.city}}</td>
    </tr>
  {% endfor %}
</table>
{% else %}
<h2>No Blood Request Available</h2>
{% endif %}
</div>
{% endblock %}

donor/templates/base.html
<!DOCTYPE html>
{% load static %}
<!--html start-->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'head.html' %}
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}
<!-- header -->
    {% include 'header.html' %}
{% block javascript %}
<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
{% endblock %}
<!-- Sidebar and content section start-->
{% endblock body %}
{% block scripts %}
{% endblock %}
</body>
</html>
<!--html end-->

donor/templates/become_donor.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body %}
<div class="container">
    <form method="POST" action="{% url 'donor:add_donor' %}" enctype="multipart/form-data"> {% csrf_token %}
<div class="row mt-1">
    <div class="form-group col-md-12">
        <label><i style="font-weight: bold;">Username</i></label>
        <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username" required>
    </div>
</div>

<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">First Name</i></label>
        <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Enter First Name" required>
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Last Name</i></label>
        <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Enter Last Name" required>
    </div>
</div>

<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Email ID</i></label>
        <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email ID" required>
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Contact Number</i></label>
        <input type="tel" class="form-control" name="phone" id="phone" placeholder="Enter Contact Number" required>
    </div>
</div>

<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">State</i></label>
        <input type="text" class="form-control" name="state" id="state" placeholder="Enter State" required>
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">City</i></label>
        <input type="text" class="form-control" name="city" id="city" placeholder="Enter City" required>
    </div>
</div>

<div class="row mt-1">
    <div class="form-group col-md-12">
        <label><i style="font-weight: bold;">Address</i></label>
        <textarea class="form-control" id="address" name="address" rows="3" placeholder="Enter Address" required></textarea>
    </div>
</div>

<div class="row mt-2">
<div class="form-group col-md-6">
    <label><i style="font-weight: bold;">Gender</i></label>
<div style="border: 1px solid lightgrey; padding: 5px; border-radius: 6px;">
<div class="form-check form-check-inline">
    <input class="form-check-input" type="radio" name="gender" id="male" value="Male">
    <label class="form-check-label">Male</label>
  </div>
  <div class="form-check form-check-inline">
    <input class="form-check-input" type="radio" name="gender" id="female" value="Female">
    <label class="form-check-label">Female</label>
  </div>
  </div>
  </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Blood Group</i></label>
        {% render_field form.blood_group class="form-control" %}
    </div>
</div>

<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Profile Photo</i></label>
        <input type="file" class="form-control" id="image" name="image" required>
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Date Of Birth</i></label>
        <input type="date" class="form-control" id="date" name="date_of_birth" required>
    </div>
</div>

<div class="row mt-1">
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Password</i></label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password" required>
    </div>
    <div class="form-group col-md-6">
        <label><i style="font-weight: bold;">Confirm Password</i></label>
        <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="Confirm Password" required>
    </div>
</div>

<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock %}

donor/templates/footer.html
{% load static %}
{% if flag is True %}
<div class="inner-wrapper">
    <div class="main-content error_403-content">
        <div class="main-content">
            <!-- copyright section starts -->
            <div class="copyright-section box-border">
                {{ flag }}
                <!--here display dynamic year-->
                <p>Copyright © {% now 'Y' %} <a href="{% url 'users:dashboard' %}" title="BTRM">BTRM</a>. All rights reserved.</p>
            </div>
            <!-- copyright section ends -->
        </div>
    </div>
</div>
{% else %}
<div class="extended-main-content">
    <!-- copyright section starts -->
    {% if required_extended %}
    <div class="extended-copyright-section box-border">
        <p class="pt-3 pb-3 pl-3 m-0">Copyright © {% now 'Y' %} <a href="{% url 'users:dashboard' %}" title="BTRM">BTRM</a>. All rights reserved.</p>
    {% else %}
    <div class="copyright-section box-border">
        <!--here display dynamic year-->
        <p class=" pl-2 m-0">Copyright © {% now 'Y' %} <a href="{% url 'users:dashboard' %}" title="BTRM">BTRM</a>. All rights reserved.</p>
    {% endif %}

   </div>
   <!-- copyright section ends -->
    </div></div>
{% endif %}
    {% block javascript %}

    <!-- SCRIPTS -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/chart.min.js' %} "></script>
    <script type="text/javascript"
            src="{% static 'js/chartjs-plugin-doughnutlabel.min.js' %} "></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>


    <!-- SCRIPTS -->
    <script type="text/javascript"
            src="{% static 'js/moment.min.js' %} "></script>
     <script type="text/javascript"
                src="{% static 'js/tempusdominus_bootstrap.js' %} "></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/chosen.jquery.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>

    <!-- Font Awesome JS-->
    <script type="text/javascript" src="{% static 'js/fontawesome-free-5.11.2-web.all.min.js' %}"></script>

    {% include 'partials/add_toaster.html' %}
    <!--validation js-->
    <script type="text/javascript" src="{% static 'js/parsley.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/djParsley.js' %}"></script>

    <!-- custom js -->
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    {% endblock %}

donor/templates/head.html
{% load static %}
<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap"
      rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" rel="stylesheet"/>
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >

<!-- Fontawesome CSS -->
<link rel="stylesheet" href="{% static 'css/all.min.css' %}">

<!--toastr css-->
<link rel="stylesheet" type="text/css" href="{% static 'css/toastr.css' %}" media="all">
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
<link rel="stylesheet" href="{% static 'css/chosen.css' %}">

donor/templates/header.html
{% load static %}
{% block body %}
<div class="container">
<h1>Available Donors According To Blood Group</h1>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for i in all_group %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm border-danger">
            <div class="card-body">
              <h3 class="card-text">Blood Group: {{i.name}}</h3>
              <h3 class="card-text">Total Donor: {{i.total}}</h3>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="/donors_list/{{i.id}}/" class="btn btn-sm btn-outline-danger">View All Donors</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

donor/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
<h1>Available Donors According To Blood Group</h1>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for i in all_group %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm border-danger">
            <div class="card-body">
              <h3 class="card-text">Blood Group: {{i.name}}</h3>
              <h3 class="card-text">Total Donor: {{i.total}}</h3>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="/donors_list/{{i.id}}/" class="btn btn-sm btn-outline-danger">View All Donors</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

donor/templates/partials/add_toaster.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/toastr.css' %}" media="all">
<!--toastr js-->
<script type="text/javascript" src="{% static 'js/toastr.min.js' %}"></script>
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message | safe }}')
                </script>
            {% elif message.tags == 'info' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message | safe }}')</script>
            {% elif message.tags == 'warning' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message | safe }}')</script>
            {% elif message.tags == 'error' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message | safe }}')</script>
            {% endif %}
        {% endfor %}
    {% endif %}